# .pre-commit-config.yaml - 预提交钩子配置
# 用于在提交前自动检查代码质量

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        name: 删除行尾空格
      - id: end-of-file-fixer
        name: 确保文件以换行符结尾
      - id: check-yaml
        name: 检查YAML文件语法
      - id: check-added-large-files
        name: 检查大文件
        args: ['--maxkb=500']
      - id: check-merge-conflict
        name: 检查是否包含合并冲突标记

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        name: C++代码格式化
        types_or: [c++, c]
        args: ['-i']

  - repo: local
    hooks:
      - id: cmake-format
        name: CMakeLists.txt格式化
        entry: cmake-format
        language: python
        files: CMakeLists.txt$
        additional_dependencies: [cmake_format]