logs:
  - name: root
    level: info
    appenders:
      - type: FileLogAppender
        path: /home/szy/code/CIM/bin/log/root.log
        rotate_type: minute
      - type: StdoutLogAppender
        
  - name: system
    level: info
    appenders:
      - type: FileLogAppender
        path: /home/szy/code/CIM/bin/log/system.log
        rotate_type: minute
      - type: StdoutLogAppender