logs:
  - name: root
    level: Info
    formatter: "%d%T%m%n"
    appenders:
      - type: FileLogAppender
        path: /home/szy/code/sylar/bin/log/root.log
        formatter: "%d%T%t%T%m%n"
        rotate_type: minute
      - type: StdoutLogAppender
        formatter: "%d%T<%f:%l>%m%n"
        
  - name: system
    level: debug
    formatter: "%d%T%m%n"
    appenders:
      - type: FileLogAppender
        path: /home/szy/code/sylar/bin/log/system.log
        level: DEBUG
        formatter: "%d%T<%f:%l>%m%n"
        rotate_type: Minute
      - type: StdoutLogAppender