logs:
  - name: root
    level: info
    formatter: "%d%T%m%n"
    appenders:
      - type: FileLogAppender
        file: /home/szy/code/sylar/bin/log/root.log
      - type: StdoutLogAppender
        formatter: "%d%T<%f:%l>%m%n"
        
  - name: system
    level: debug
    formatter: "%d%T%m%n"
    appenders:
      - type: FileLogAppender
        file: /home/szy/code/sylar/bin/log/system.log
        level: info
        formatter: "%d%T<%f:%l>%m%n"
      - type: StdoutLogAppender