system:
  port: 9999
  value: 15.0
  name: "updated_sylar"
  int_ver:
    - 1
    - 2
    - 3
    - 4
  int_list:
    - 90
    - 80
  int_set:
    - 200
    - 300
    - 400
  int_unordered_set:
    - 1000
    - 2000
    - 3000
  int_map:
    key1: 10
    key2: 20
  int_unordered_map:
    map_key1: 100
    map_key2: 200
    map_key3: 300

class:
  person:
    name: "zhangsan"
    age: 22
    sex: true